#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Author: Leon Jung, Gilbert
 
import rospy
import numpy as np
from std_msgs.msg import Float64,String
from geometry_msgs.msg import Twist

class ControlLane():
    def __init__(self):
        self.sub_lane = rospy.Subscriber('/control/lane', Float64, self.cbFollowLane, queue_size = 1)
        self.sub_max_vel = rospy.Subscriber('/control/max_vel', Float64, self.cbGetMaxVel, queue_size = 1)
        self.pub_cmd_vel = rospy.Publisher('/control/cmd_vel', Twist, queue_size = 1)
        self.sub_cmd = rospy.Subscriber('/cmd', String, self.cmd_control, queue_size = 1)
        self.lastError = 0
        self.MAX_VEL = 0.06
        self.stop = False
	self.stop_sign =False
	self.inter = False
        self.lastAngular = 0
        rospy.on_shutdown(self.fnShutDown)

    def cmd_control(self,cmd):
        if cmd == "stop":
	    self.stop_sign= True
	elif cmd =="inter":
	    self.inter = True
        elif cmd == "go":
            rospy.loginfo("restart. the bot would run again")
            self.stop = False    
	    self.stop_sign =False
	    self.inter = False
	if self.stop_sign == True and self.inter == True:
	   self.stop= True


    def cbGetMaxVel(self, max_vel_msg):
        self.MAX_VEL = max_vel_msg.data

    def cbFollowLane(self, desired_center):
        center = desired_center.data

        error = center - 500

        Kp = 0.002
        Kd = 0.004

        angular_z = Kp * error + Kd * (error - self.lastError)
        diff_angular = angular_z - self.lastAngular
        print(diff_angular)
        '''
        if(diff_angular > threshold):
            rospy.sleep(1.0)
        '''
        self.lastAngular = angular_z
        # print(angular_z)
        self.lastError = error
        twist = Twist()
        if not self.stop:
            twist.linear.x = min(self.MAX_VEL * ((1 - abs(error) / 500) ** 2.2), 0.2)
            twist.angular.z = -max(angular_z, -2.0) if angular_z < 0 else -min(angular_z, 2.0)
        else:
            twist.linear.x = 0
            twist.angular.z = 0
        twist.linear.y = 0
        twist.linear.z = 0
        twist.angular.x = 0
        twist.angular.y = 0
            
        
        self.pub_cmd_vel.publish(twist)

    def fnShutDown(self):
        rospy.loginfo("Shutting down. cmd_vel will be 0")

        twist = Twist()
        twist.linear.x = 0
        twist.linear.y = 0
        twist.linear.z = 0
        twist.angular.x = 0
        twist.angular.y = 0
        twist.angular.z = 0
        self.pub_cmd_vel.publish(twist) 

    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('control_lane')
    node = ControlLane()
    node.main()
